import type { RawFacility } from "./types";

// 10 sample Indian hospital records, intentionally messy to showcase the engine
export const SAMPLE_FACILITIES: RawFacility[] = [
  {
    facility_name: "Jalal Medical Center",
    city: "Motihari",
    district: "Motihari",
    state: "Bihar",
    bed_count: 0,
    icu_available: false,
    oxygen_available: false,
    ambulance_available: false,
    emergency_24x7: true,
    specialist_available: "Emergency Care, Surgery",
    unstructured_notes:
      "Trust score: 85 (VERIFIED).\nReasoning: 24x7 emergency services, including surgery.\nEvidence: This facility lists surgery services but we couldn't confirm a surgeon on staff.",
    latitude: 26.648085,
    longitude: 84.93428,
  },
  {
    facility_name: "Shree Pradhan Hospital",
    city: "Muzaffarpur",
    district: "Muzaffarpur",
    state: "Bihar",
    bed_count: 0,
    icu_available: false,
    oxygen_available: false,
    ambulance_available: false,
    emergency_24x7: true,
    specialist_available: "Emergency Care, General Surgery",
    unstructured_notes:
      "Trust score: 60 (USE WITH CAUTION).\nReasoning: Emergency Service 24x7, General Surgery.\nEvidence: Limited information available about their emergency services.",
    latitude: 26.105175,
    longitude: 85.370598,
  },
  {
    facility_name: "Bommineni Hospitals",
    city: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    bed_count: 0,
    icu_available: false,
    oxygen_available: false,
    ambulance_available: false,
    emergency_24x7: false,
    specialist_available: "General Medicine",
    unstructured_notes:
      "Trust score: 85 (VERIFIED).\nReasoning: General medical services that can cater to eye care needs.\nEvidence: Verified facility.",
    latitude: 17.394073,
    longitude: 78.339813,
  },
  {
    facility_name: "Dr V K Garg Clinic",
    city: "Jaipur",
    district: "Jaipur",
    state: "Rajasthan",
    bed_count: 0,
    icu_available: false,
    oxygen_available: false,
    ambulance_available: false,
    emergency_24x7: false,
    specialist_available: "Neonatal Care, Pediatrics",
    unstructured_notes:
      "Trust score: 85 (VERIFIED).\nReasoning: Expertise in neonatal care and child care, linked with a prestigious medical institution.\nEvidence: Verified facility.",
    latitude: 26.963406,
    longitude: 75.760483,
  },
  {
    facility_name: "New Fortis Hospital",
    city: "Padrauna",
    district: "Padrauna",
    state: "Uttar Pradesh",
    bed_count: 0,
    icu_available: false,
    oxygen_available: false,
    ambulance_available: false,
    emergency_24x7: false,
    specialist_available: "Dialysis, Nephrology",
    unstructured_notes:
      "Trust score: 85 (VERIFIED).\nReasoning: Dialysis services.\nEvidence: Verified facility.",
    latitude: 26.901669,
    longitude: 83.983795,
  },
  {
    facility_name: "Sai Children Hospital",
    city: "Kalvan",
    district: "Kalvan",
    state: "Maharashtra",
    bed_count: 0,
    icu_available: true,
    oxygen_available: false,
    ambulance_available: false,
    emergency_24x7: false,
    specialist_available: "ICU, Neonatal Care, Pediatrics",
    unstructured_notes:
      "Trust score: 85 (VERIFIED).\nReasoning: ICU and neonatal care services.\nEvidence: This facility lists ICU services but we have some concerns about the availability of equipment.",
    latitude: 20.493168,
    longitude: 74.03019,
  },
  {
    facility_name: "Advance Dental Care and Implant Clinic",
    city: "Delhi",
    district: "Delhi",
    state: "Delhi",
    bed_count: 0,
    icu_available: false,
    oxygen_available: false,
    ambulance_available: false,
    emergency_24x7: false,
    specialist_available: "Dentistry, Implants",
    unstructured_notes:
      "Trust score: 85 (VERIFIED).\nReasoning: Dental services including implant procedures.\nEvidence: Verified facility.",
    latitude: 28.534542,
    longitude: 77.230347,
  },
];
