import * as XLSX from 'xlsx';
import { writeFileSync } from 'fs';

const rows = [
  { facility_name:"Apollo Multispeciality Hospital", city:"Chennai", district:"Chennai", state:"Tamil Nadu", bed_count:320, icu_available:"yes", oxygen_available:"yes", ambulance_available:"yes", emergency_24x7:"yes", specialist_available:"Cardiology, Neurology, Advanced Surgery, Orthopedic", unstructured_notes:"Fully equipped with 24 ICU beds, 12 ventilators, ample oxygen cylinders, defibrillators, CT scan and MRI machines. Round-the-clock emergency. Anesthesiologists, cardiologists, surgeons, and 80+ nurses on staff.", latitude:13.0827, longitude:80.2707 },
  { facility_name:"Sundar Clinic & Nursing Home", city:"Patna", district:"Patna", state:"Bihar", bed_count:18, icu_available:"yes", oxygen_available:"no", ambulance_available:"yes", emergency_24x7:"yes", specialist_available:"Advanced Surgery, Gynecology", unstructured_notes:"Small private clinic. ICU room exists but ventilator broken since last year. No oxygen supply currently. Night emergency closed, day only. One MBBS doctor and 2 nurses.", latitude:25.5941, longitude:85.1376 },
  { facility_name:"AIIMS New Delhi", city:"New Delhi", district:"New Delhi", state:"Delhi", bed_count:2478, icu_available:"yes", oxygen_available:"yes", ambulance_available:"yes", emergency_24x7:"yes", specialist_available:"Cardiology, Neurology, Oncology, Advanced Surgery, Pediatrics", unstructured_notes:"Premier institute. 200+ ICU beds, 150 ventilators, oxygen plant on site, multiple defibrillators, CT, MRI, ultrasound, dialysis units. Anesthesiologists, surgeons, cardiologists, paediatricians, gynecologists, radiologists, neurologists. 24/7 emergency.", latitude:28.5672, longitude:77.21 },
  { facility_name:"Rural PHC Bardhaman", city:"Bardhaman", district:"Purba Bardhaman", state:"West Bengal", bed_count:6, icu_available:"no", oxygen_available:"yes", ambulance_available:"no", emergency_24x7:"no", specialist_available:"General Physician", unstructured_notes:"Primary health centre. Oxygen cylinders available. No ICU, no ambulance. One general physician and 2 nurses. Operates 9am-5pm.", latitude:23.2324, longitude:87.8615 },
  { facility_name:"Krishna Heart Care", city:"Ahmedabad", district:"Ahmedabad", state:"Gujarat", bed_count:95, icu_available:"yes", oxygen_available:"yes", ambulance_available:"yes", emergency_24x7:"yes", specialist_available:"Cardiology, Cardiac Surgery", unstructured_notes:"Cardiac specialty hospital. CCU with 18 beds, ventilators, defibrilators, ECG, oxygen cyliners. Cardiologists and surgeons available. Anaesthetist on call 24x7. Ambulance fleet of 4.", latitude:23.0225, longitude:72.5714 },
  { facility_name:"Janaki Maternity Home", city:"Lucknow", district:"Lucknow", state:"Uttar Pradesh", bed_count:30, icu_available:"no", oxygen_available:"yes", ambulance_available:"yes", emergency_24x7:"yes", specialist_available:"Gynecology, Pediatrics", unstructured_notes:"Maternity focused. OT for c-sections, oxygen supply, ultrasound machine. Gynaecologist and pediatrician on staff. Nurses available 24 hours. No ICU.", latitude:26.8467, longitude:80.9462 },
  { facility_name:"Hope Diagnostic & Hospital", city:"Bhopal", district:"Bhopal", state:"Madhya Pradesh", bed_count:60, icu_available:"yes", oxygen_available:"yes", ambulance_available:"no", emergency_24x7:"no", specialist_available:"Radiology, General Physician", unstructured_notes:"Diagnostic centre with inpatient ward. CT scan, X-ray, ultrasound, ECG. ICU has 4 beds but no ventilator. Oxygen tanks available. Ambulance unavailable currently.", latitude:23.2599, longitude:77.4126 },
  { facility_name:"Greenfields Mission Hospital", city:"Kochi", district:"Ernakulam", state:"Kerala", bed_count:220, icu_available:"yes", oxygen_available:"yes", ambulance_available:"yes", emergency_24x7:"yes", specialist_available:"Cardiology, Orthopedic, Advanced Surgery, Neurology", unstructured_notes:"Mission hospital. 30 ICU beds with full ventilator support, oxygen plant, defibrillators, CT, MRI, dialysis. Surgeons, anesthesiologists, orthopedic, neurologists on roster. Emergency 24/7 with night ambulance team.", latitude:9.9312, longitude:76.2673 },
  { facility_name:"Shanti Care Polyclinic", city:"Ranchi", district:"Ranchi", state:"Jharkhand", bed_count:12, icu_available:"no", oxygen_available:"no", ambulance_available:"no", emergency_24x7:"no", specialist_available:"General Physician", unstructured_notes:"Outpatient polyclinic. No emergency services. ECG machine available. One doctor.", latitude:23.3441, longitude:85.3096 },
  { facility_name:"Maharaja Specialty Centre", city:"Jaipur", district:"Jaipur", state:"Rajasthan", bed_count:140, icu_available:"yes", oxygen_available:"yes", ambulance_available:"yes", emergency_24x7:"yes", specialist_available:"Advanced Surgery, Orthopedic, Cardiology", unstructured_notes:"Multi-specialty. ICU 12 beds, oxygen cylinders, defib, X-ray, CT scan, ultrasound. Surgeons and orthopedic doctors on staff. Anesthesiologist not available currently. Ambulance 2 units. 24/7 emergency.", latitude:26.9124, longitude:75.7873 },
];

const ws = XLSX.utils.json_to_sheet(rows);
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Facilities");
const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
writeFileSync("/mnt/documents/sample-hospitals.xlsx", buf);
console.log("wrote", buf.length, "bytes");
